config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  get '/mypage', to: 'mypage#show'
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  ActiveRecord::Base.connection.execute("SELECT setval('articles_id_seq', coalesce((SELECT MAX(id)+1 FROM articles), 1), false)")
  before_action :set_article, only: [:edit, :update, :destroy]

  def index
    user = current_user
    @articles = user.articles
  end

  def show
    user = current_user
    @articles = user.articles.search(params[:search]).page(params[:page]).per(10)
    # @articles = user.articles.page(params[:page]).per(10)

  end

  def new
  end

  def edit
  end


  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to @article, notice: "#{t('activerecord.models.article')}を作成しました。"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article,notice: "#{t('activerecord.models.article')}を編集しました。"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: "#{t('activerecord.models.article')}を削除しました。"
  end



  private
    def article_params
      params.require(:article).permit(:title,:content)
    end

    def set_article
      @article = current_user.articles.find(params[:id])
    end
  end

app/views/mypage/_search.html.erb
<%= form_with url: mypage_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label 'タイトル', class: "form-label" %>
        <%= form.text_field :search, value: params[:search], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/mypage/show.html.erb
<p id="notice"><%= notice %></p>

<h1>記事</h1>
   <%= render partial: "search" %>

<% if user_signed_in? %>
  <%= link_to '記事作成', new_article_path, class: "btn btn-info"%>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td>
          <%= article.title %>
          <% article.tags.each do |tag| %>
            <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
          <% end %>
        </td>
        <td><%= article.content %></td>

        <% if user_signed_in? %>
          <td>
            <%= link_to '詳細', article, class: "btn btn-success" %>
            <%= link_to '編集', edit_article_path(article), class: "btn btn-warning" %>
            <%= link_to '削除', article, class: "btn btn-danger", method: :delete, data: { confirm: '削除しますか？' } %>
          </td>
        <% else %>
          <td>
            <%= link_to '詳細', article, class: "btn btn-success" %>
          <td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
  <%= paginate @articles %>
</table>